[versions]
minecraft = "26.2"
compatibility = "26.2.x"
fabric-api = "0.158.0+26.2"

modmenu = "njXb639R"
caxton = "wVI9Rvrv"
entityculling = "iiF6U3Ne"
exordium = "IK5p5vrB"
iris = "oaD6KQls"

athen = "0.3.3b+26.2"
snowbird = "024+26.2"
cascade = "040+26.2"
updater = "1.0.8+26.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

athen = { module = "foo.starred:athen", version.ref = "athen" }
snowbird = { module = "foo.starred:snowbird", version.ref = "snowbird" }
cascade = { module = "foo.starred:cascade", version.ref = "cascade" }
updater = { module = "foo.starred:updater", version.ref = "updater" }

modmenu = { module = "maven.modrinth:modmenu", version.ref = "modmenu" }
caxton = { module = "maven.modrinth:caxton", version.ref = "caxton" }
entityculling = { module = "maven.modrinth:entityculling", version.ref = "entityculling" }
exordium = { module = "maven.modrinth:exordium", version.ref = "exordium" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }